apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltak-tilsagnsbrev
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: {{min-replicas}}
    max: {{max-replicas}}
  liveness:
    path: /tiltak-tilsagnsbrev/internal/healthcheck
    initialDelay: 60
    timeout: 10
  readiness:
    path: /tiltak-tilsagnsbrev/internal/healthcheck
    initialDelay: 60
    timeout: 10
  ingresses:
    - {{ingress}}
  vault:
    enabled: true
    paths:
      - kvPath: {{vault-serviceuser-path}}
        mountPath: "/secrets/serviceuser/srvtiltak-tilsagns/"
      - kvPath: {{vault-default-path}}
        mountPath: "/var/run/secrets/nais.io/vault/"
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: {{spring-profil}}
  - name: PDL_API_SCOPE
    value: {{pdl-api-scope}}
  webproxy: true
  prometheus:
    enabled: true
    path: /tiltak-tilsagnsbrev/internal/actuator/prometheus
  resources:
    limits:
      memory: 1024Mi
  kafka:
    pool: {{kafka-pool}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
